name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-render:
    runs-on: ubuntu-latest
    env:
      render_deploy_hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
    steps:
      - name: Calling Render Deploy Hook
        run: |
          curl "$render_deploy_hook"
